version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: asdf
  DOCKER_PASS: fda
install:
  - docker version

build_script:
  - docker build -t windowsdocker:latest .

deploy_script:
  - docker login -u="tranzha" -p="test1234"
  - docker push tranzha/windowsdocker:latest