version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: tranzha
  DOCKER_PASS: test1234
install:
  - docker version

build_script:
  - docker build -t windowsdockertest .

test_script:
  - docker run windowsdockertest

deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push windowsdockertest