version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER: tranzha
  DOCKER_PASS: test1234
install:
  - docker version

build_script:
  - docker build -t windowsdocker:latest .

deploy_script:
  - docker login -u="%DOCKER_USER%" -p="%DOCKER_PASS%"
  - docker push windowsdocker:latest